# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d296bfa9ea0fccd9840de47097fcfa68cc0d99623cb0af0c8f0d45f0ad979274c114145c294a74d0bc209485e599f2431934fd25d0d888c191b0a2f8d6a77410

test:
  secret_key_base: ba76b17a1dec95dd65222e2607855032c963b045877214457dd173eafacf6c83b7f64f531e0babd7ef3d2bb7ead8dbc6514996f40b0ef3328bc44e84f1051417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
